include:
  - project: common/gitlab-ci-templates
    file: vault/gcp-key.yml

variables:
  # includeしたjobで使われるもの
  CI_VAULT_ROLE: newsdigest
  CI_VAULT_PATH: gcp/key/jxpress-fa-backlash-dev
  # このプロジェクト固有のもの
  GCP_PROJECT: jxpress-fa-backlash-dev
  GCR_IMAGE: asia.gcr.io/jxpress-fa-backlash-dev/gke-sample-app

stages:
  - test
  - push

test:
  stage: test
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  script:
    - gcloud --project ${GCP_PROJECT} auth activate-service-account --key-file .secrets/google_application_credentials.json
    - gcloud --project ${GCP_PROJECT} builds submit --tag $GCR_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - branches
    - tags

push:
  stage: push
  image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
  script:
    - gcloud --project ${GCP_PROJECT} auth activate-service-account --key-file .secrets/google_application_credentials.json
    - gcloud --project ${GCP_PROJECT} builds submit --tag $GCR_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - branches
    - tags
